name: Package

on:
  workflow_dispatch:

permissions: {}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      - name: Package Maven artifact
        run:
          mvn package
      - name: Upload Maven
        uses: actions/upload-artifact@v4
        with:
          name: maven-dependency-plugin-3.6.1-SNAPSHOT.jar
          path: target/maven-dependency-plugin-3.6.1-SNAPSHOT.jar
